on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

name: compile

jobs:
  build:
    name: Build artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install linker(aarch64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu

      - name: Add rustup target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Move binaries (Linux/MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: mv ./target/${{ matrix.target }}/release/prot-scriber ./${{ matrix.target }}_prot-scriber

      - name: Move binaries, generate manual, and include it in the README.md (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          mv ./target/${{ matrix.target }}/release/prot-scriber.exe ./${{ matrix.target }}_prot-scriber.exe
          chmod a+x ./${{ matrix.target }}_prot-scriber
          echo '<summary>click to read the `prot-scriber` manual</summary>' > prot-scriber-manual.txt
          ./${{ matrix.target }}_prot-scriber --help >> prot-scriber-manual.txt
          echo '</details>' >> prot-scriber-manual.txt
          sed -e '/summary/,/\/details/!b' -e '/\/details/!d;r prot-scriber-manual.txt' -e 'd' README.md

      - name: Binary relase (Linux/MaxOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.target }}_prot-scriber

      - name: Relase help-text / manual (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: prot-scriber-manual.txt
      
      - name: Relase (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.target }}_prot-scriber.exe
