on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

name: compile

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/armv7-unknown-linux-gnueabihf/release/prot-scriber
