on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

name: compile

jobs:
  linux_arm7:
    name: Windows 7+
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu
      - name: Find binary
        run: "echo $(find . -type f -executable | grep -P 'prot-scriber$')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/x86_64-unknown-linux-gnu/release/prot-scriber
